### ISSUE TITLE
Error while trying to parse

### ISSUE THREAD

**Issue by FMusic** [sovren/sovren-java#36]
Hello,
I get an error while trying to upload file using this library.

`java.lang.NoSuchMethodError: 'okhttp3.RequestBody okhttp3.RequestBody.create(java.lang.String, okhttp3.MediaType)'
	at com.sovren.SovrenClient.parseResume(SovrenClient.java:248) ~[sovren-java-1.2.0.jar:1.2.0]
	at demos.sovren.CvService.saveAndParse(CvService.java:41) 
	at demos.sovren.Controller.saveCv(Controller.java:29)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke
	at org.springframework.web.method.support.InvocableHandlerMethod.invoke
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocab
	at org.springframework.web.servlet.mvc.method.annotation.RequestMapping
	at org.springframework.web.servlet.mvc.method.annotation.RequestMapping
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1064)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:681) ~[tomcat-embed-core-9.0.50.jar:4.0.FR]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]`

Is there any way to solve this?
I am using JDK11 and Intellij. Dependency included with pom.xml, and I am using Spring Boot..

**Comment by sovren-jwesson** [comment]
Frane,
I believe this is related to: https://github.com/auth0/auth0-java/issues/324

It seems that Spring Boot forces the okhttp3 version to v3 while this SDK requires v4. Some solutions have been posted in that thread that you might try. Also, I see a code change that was made at the end of that thread to resolve the issue which I am going to try to implement.

Thanks for all the info. Please post any updates here, and I will do the same.

**Comment by sovren-jwesson** [comment]
This should be fixed in v1.2.1 which is available in Maven, now. If it still does not work for you, you might have to try some of the dependency solutions mentioned in that thread I linked.

Thanks again.

**Comment by FMusic** [comment]
Thank you very much, it works with new version.
